#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCS_DIR="${ROOT_DIR}/docs"
OUT_FILE="${DOCS_DIR}/aws-inventory.md"

AWS_PROFILE="${AWS_PROFILE:-default}"
AWS_REGION="${AWS_REGION:-eu-central-1}"
ACM_REGION="${ACM_REGION:-us-east-1}"

mkdir -p "${DOCS_DIR}"

write_section() {
  local title="$1"
  shift

  {
    printf "\n## %s\n\n" "${title}"
    printf '```text\n'
  } >> "${OUT_FILE}"

  if "$@" >> "${OUT_FILE}" 2>&1; then
    true
  else
    printf "\nCommand failed: %s\n" "$*" >> "${OUT_FILE}"
  fi

  {
    printf '```\n'
  } >> "${OUT_FILE}"
}

cat > "${OUT_FILE}" <<EOF
# AWS Inventory

Generated by \`scripts/aws-inventory.sh\`.

- AWS profile: \`${AWS_PROFILE}\`
- AWS region: \`${AWS_REGION}\`
- ACM region: \`${ACM_REGION}\`

EOF

write_section "Caller Identity" \
  aws sts get-caller-identity \
    --profile "${AWS_PROFILE}" \
    --region "${AWS_REGION}" \
    --output table

write_section "ACM Certificates (${ACM_REGION})" \
  aws acm list-certificates \
    --profile "${AWS_PROFILE}" \
    --region "${ACM_REGION}" \
    --certificate-statuses ISSUED \
    --output table

if [[ "${ACM_REGION}" != "${AWS_REGION}" ]]; then
  write_section "ACM Certificates (${AWS_REGION})" \
    aws acm list-certificates \
      --profile "${AWS_PROFILE}" \
      --region "${AWS_REGION}" \
      --certificate-statuses ISSUED \
      --output table
fi

write_section "Lambda Functions" \
  aws lambda list-functions \
    --profile "${AWS_PROFILE}" \
    --region "${AWS_REGION}" \
    --query 'Functions[].{Name:FunctionName,Runtime:Runtime,Memory:MemorySize,Timeout:Timeout,Updated:LastModified,Role:Role}' \
    --output table

write_section "API Gateway HTTP APIs" \
  aws apigatewayv2 get-apis \
    --profile "${AWS_PROFILE}" \
    --region "${AWS_REGION}" \
    --query 'Items[].{Name:Name,ApiId:ApiId,Protocol:ProtocolType,Endpoint:ApiEndpoint}' \
    --output table

write_section "API Gateway REST APIs" \
  aws apigateway get-rest-apis \
    --profile "${AWS_PROFILE}" \
    --region "${AWS_REGION}" \
    --query 'items[].{Name:name,ApiId:id,Created:createdDate}' \
    --output table

write_section "CloudFront Distributions" \
  aws cloudfront list-distributions \
    --profile "${AWS_PROFILE}" \
    --query 'DistributionList.Items[].{Id:Id,Domain:DomainName,Aliases:Aliases.Items,Enabled:Enabled,Status:Status,Origins:Origins.Items[].DomainName}' \
    --output table

write_section "S3 Buckets" \
  aws s3api list-buckets \
    --profile "${AWS_PROFILE}" \
    --query 'Buckets[].{Name:Name,Created:CreationDate}' \
    --output table

write_section "Lambda Log Groups" \
  aws logs describe-log-groups \
    --profile "${AWS_PROFILE}" \
    --region "${AWS_REGION}" \
    --log-group-name-prefix /aws/lambda \
    --query 'logGroups[].{Name:logGroupName,Retention:retentionInDays,StoredBytes:storedBytes}' \
    --output table

write_section "Route 53 Hosted Zones" \
  aws route53 list-hosted-zones \
    --profile "${AWS_PROFILE}" \
    --query 'HostedZones[].{Name:Name,Id:Id,Private:Config.PrivateZone}' \
    --output table

echo "Wrote ${OUT_FILE}"

