#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCS_DIR="${ROOT_DIR}/docs"
OUT_FILE="${DOCS_DIR}/aws-detail-inventory.md"

AWS_PROFILE="${AWS_PROFILE:-default}"
AWS_REGION="${AWS_REGION:-eu-central-1}"
ACM_REGION="${ACM_REGION:-us-east-1}"

LAMBDA_FUNCTION="${LAMBDA_FUNCTION:-MandelbrotFRA}"
API_NAME="${API_NAME:-MandelbrotFRA}"
API_ID="${API_ID:-}"
BUCKET_NAME="${BUCKET_NAME:-mandelbro-bucket}"
DISTRIBUTION_ID="${DISTRIBUTION_ID:-E3VOOYYQE4GTM7}"
CERT_DOMAIN="${CERT_DOMAIN:-*.i-dmytro.org}"
CUSTOM_DOMAIN="${CUSTOM_DOMAIN:-fractal.i-dmytro.org}"

mkdir -p "${DOCS_DIR}"

aws_cmd() {
  aws --profile "${AWS_PROFILE}" --region "${AWS_REGION}" "$@"
}

aws_global_cmd() {
  aws --profile "${AWS_PROFILE}" "$@"
}

aws_acm_cmd() {
  aws --profile "${AWS_PROFILE}" --region "${ACM_REGION}" "$@"
}

write_section() {
  local title="$1"
  shift

  {
    printf "\n## %s\n\n" "${title}"
    printf '```text\n'
  } >> "${OUT_FILE}"

  if "$@" >> "${OUT_FILE}" 2>&1; then
    true
  else
    printf "\nCommand failed: %s\n" "$*" >> "${OUT_FILE}"
  fi

  {
    printf '```\n'
  } >> "${OUT_FILE}"
}

value_or_empty() {
  local value="$1"
  if [[ "${value}" == "None" || "${value}" == "null" ]]; then
    printf ""
  else
    printf "%s" "${value}"
  fi
}

discover_api_id() {
  if [[ -n "${API_ID}" ]]; then
    printf "%s" "${API_ID}"
    return
  fi

  local discovered
  discovered="$(aws_cmd apigatewayv2 get-apis \
    --query "Items[?Name=='${API_NAME}'].ApiId | [0]" \
    --output text 2>/dev/null || true)"
  value_or_empty "${discovered}"
}

discover_cert_arn() {
  local discovered
  discovered="$(aws_acm_cmd acm list-certificates \
    --certificate-statuses ISSUED \
    --query "CertificateSummaryList[?DomainName=='${CERT_DOMAIN}'].CertificateArn | [0]" \
    --output text 2>/dev/null || true)"
  value_or_empty "${discovered}"
}

API_ID="$(discover_api_id)"
CERT_ARN="$(discover_cert_arn)"

cat > "${OUT_FILE}" <<EOF
# AWS Detailed Inventory

Generated by \`scripts/aws-detail-inventory.sh\`.

This file is intentionally ignored by Git. It may contain account IDs, ARNs,
resource names, policy details, and deployment topology.

- AWS profile: \`${AWS_PROFILE}\`
- AWS region: \`${AWS_REGION}\`
- ACM region: \`${ACM_REGION}\`
- Lambda function: \`${LAMBDA_FUNCTION}\`
- API name: \`${API_NAME}\`
- API ID: \`${API_ID:-not discovered}\`
- S3 bucket: \`${BUCKET_NAME}\`
- CloudFront distribution: \`${DISTRIBUTION_ID}\`
- Certificate domain: \`${CERT_DOMAIN}\`
- Certificate ARN: \`${CERT_ARN:-not discovered}\`
- Custom domain: \`${CUSTOM_DOMAIN}\`

EOF

write_section "DNS Resolution (${CUSTOM_DOMAIN})" \
  getent hosts "${CUSTOM_DOMAIN}"

write_section "Caller Identity" \
  aws_cmd sts get-caller-identity --output json

write_section "Lambda Configuration (${LAMBDA_FUNCTION})" \
  aws_cmd lambda get-function-configuration \
    --function-name "${LAMBDA_FUNCTION}" \
    --query '{FunctionName:FunctionName,FunctionArn:FunctionArn,Runtime:Runtime,Role:Role,Handler:Handler,CodeSize:CodeSize,Description:Description,Timeout:Timeout,MemorySize:MemorySize,LastModified:LastModified,CodeSha256:CodeSha256,Version:Version,TracingConfig:TracingConfig,RevisionId:RevisionId,State:State,StateReason:StateReason,StateReasonCode:StateReasonCode,PackageType:PackageType,Architectures:Architectures,EphemeralStorage:EphemeralStorage,LoggingConfig:LoggingConfig}' \
    --output json

write_section "Lambda Function URL (${LAMBDA_FUNCTION})" \
  aws_cmd lambda get-function-url-config \
    --function-name "${LAMBDA_FUNCTION}" \
    --output json

write_section "Lambda Resource Policy (${LAMBDA_FUNCTION})" \
  aws_cmd lambda get-policy \
    --function-name "${LAMBDA_FUNCTION}" \
    --output json

ROLE_ARN="$(aws_cmd lambda get-function-configuration \
  --function-name "${LAMBDA_FUNCTION}" \
  --query 'Role' \
  --output text 2>/dev/null || true)"
ROLE_ARN="$(value_or_empty "${ROLE_ARN}")"
ROLE_NAME="${ROLE_ARN##*/}"

if [[ -n "${ROLE_NAME}" ]]; then
  write_section "Lambda IAM Role (${ROLE_NAME})" \
    aws_global_cmd iam get-role \
      --role-name "${ROLE_NAME}" \
      --output json

  write_section "Lambda IAM Attached Policies (${ROLE_NAME})" \
    aws_global_cmd iam list-attached-role-policies \
      --role-name "${ROLE_NAME}" \
      --output json

  write_section "Lambda IAM Inline Policy Names (${ROLE_NAME})" \
    aws_global_cmd iam list-role-policies \
      --role-name "${ROLE_NAME}" \
      --output json
fi

if [[ -n "${API_ID}" ]]; then
  write_section "API Gateway HTTP API (${API_ID})" \
    aws_cmd apigatewayv2 get-api \
      --api-id "${API_ID}" \
      --output json

  write_section "API Gateway Routes (${API_ID})" \
    aws_cmd apigatewayv2 get-routes \
      --api-id "${API_ID}" \
      --output json

  write_section "API Gateway Integrations (${API_ID})" \
    aws_cmd apigatewayv2 get-integrations \
      --api-id "${API_ID}" \
      --output json

  write_section "API Gateway Stages (${API_ID})" \
    aws_cmd apigatewayv2 get-stages \
      --api-id "${API_ID}" \
      --output json
fi

write_section "API Gateway Custom Domains" \
  aws_cmd apigatewayv2 get-domain-names \
    --output json

write_section "CloudFront Distribution (${DISTRIBUTION_ID})" \
  aws_global_cmd cloudfront get-distribution \
    --id "${DISTRIBUTION_ID}" \
    --output json

write_section "CloudFront Distribution Config (${DISTRIBUTION_ID})" \
  aws_global_cmd cloudfront get-distribution-config \
    --id "${DISTRIBUTION_ID}" \
    --output json

write_section "S3 Bucket Location (${BUCKET_NAME})" \
  aws_global_cmd s3api get-bucket-location \
    --bucket "${BUCKET_NAME}" \
    --output json

write_section "S3 Public Access Block (${BUCKET_NAME})" \
  aws_global_cmd s3api get-public-access-block \
    --bucket "${BUCKET_NAME}" \
    --output json

write_section "S3 Bucket Policy Status (${BUCKET_NAME})" \
  aws_global_cmd s3api get-bucket-policy-status \
    --bucket "${BUCKET_NAME}" \
    --output json

write_section "S3 Bucket Policy (${BUCKET_NAME})" \
  aws_global_cmd s3api get-bucket-policy \
    --bucket "${BUCKET_NAME}" \
    --output json

write_section "S3 Bucket CORS (${BUCKET_NAME})" \
  aws_global_cmd s3api get-bucket-cors \
    --bucket "${BUCKET_NAME}" \
    --output json

write_section "S3 Bucket Website (${BUCKET_NAME})" \
  aws_global_cmd s3api get-bucket-website \
    --bucket "${BUCKET_NAME}" \
    --output json

write_section "S3 Bucket Encryption (${BUCKET_NAME})" \
  aws_global_cmd s3api get-bucket-encryption \
    --bucket "${BUCKET_NAME}" \
    --output json

write_section "S3 Bucket Versioning (${BUCKET_NAME})" \
  aws_global_cmd s3api get-bucket-versioning \
    --bucket "${BUCKET_NAME}" \
    --output json

write_section "S3 Bucket Lifecycle (${BUCKET_NAME})" \
  aws_global_cmd s3api get-bucket-lifecycle-configuration \
    --bucket "${BUCKET_NAME}" \
    --output json

write_section "S3 Top-Level Objects (${BUCKET_NAME})" \
  aws_global_cmd s3api list-objects-v2 \
    --bucket "${BUCKET_NAME}" \
    --max-items 25 \
    --query '{KeyCount:KeyCount,Objects:Contents[].{Key:Key,Size:Size,LastModified:LastModified,ETag:ETag}}' \
    --output json

write_section "CloudWatch Lambda Log Group" \
  aws_cmd logs describe-log-groups \
    --log-group-name-prefix "/aws/lambda/${LAMBDA_FUNCTION}" \
    --output json

write_section "Recent Lambda Log Streams" \
  aws_cmd logs describe-log-streams \
    --log-group-name "/aws/lambda/${LAMBDA_FUNCTION}" \
    --order-by LastEventTime \
    --descending \
    --max-items 10 \
    --query 'logStreams[].{Name:logStreamName,LastEvent:lastEventTimestamp,StoredBytes:storedBytes}' \
    --output json

if [[ -n "${CERT_ARN}" ]]; then
  write_section "ACM Certificate (${CERT_DOMAIN})" \
    aws_acm_cmd acm describe-certificate \
      --certificate-arn "${CERT_ARN}" \
      --output json
fi

echo "Wrote ${OUT_FILE}"
